### ISSUE TITLE
Wp-D3 appears to break ad insertion.

### ISSUE THREAD

**Issue by benlk** [Automattic/super-cool-ad-inserter-plugin#35]
Plugin: https://wordpress.org/plugins/wp-d3/

Internal discussion: https://secure.helpscout.net/conversation/443084002/1341/?folderId=1211654

Activating Wp-D3 prevents SCAIP ad insertion.

Deactivating the plugin re-enables SCAIP ad insertion.

This may be a bug in SCAIP or in Wp-D3; we should report it to the maintainer if we have time.

**Comment by adekbadek** [comment]
WP-D3 seems unmaintained, and there are very little active installations. Closing for now.
