### ISSUE TITLE
Are any changes necessary after Gutenberg added support for the 'disabled' attribute in SelectControl options?

### ISSUE THREAD

**Issue by benlk** [Automattic/super-cool-ad-inserter-plugin#48]
https://github.com/WordPress/gutenberg/issues/11270 is an issue we opened because Gutenberg didn't support passing the `disabled` HTML attribute to the `<option>` of a `<select>`.

That's been fixed in Gutenberg in https://github.com/WordPress/gutenberg/commit/7d2006619aed575a3f9b19f34e84fb4cd70248a0, in https://github.com/WordPress/gutenberg/pull/15976, sometime around Gutenberg 6.2.0

**Comment by adekbadek** [comment]
I can see the [`disabled` option here](https://github.com/Automattic/super-cool-ad-inserter-plugin/blob/5e07a044ad72c7ba0fe2a524c8e0afdcc4d84723/blocks/scaip-sidebar/block.js#L72) is working as expected.
