### ISSUE TITLE
Injection appears to not differentiate child <p> from parent <p> 

### ISSUE THREAD

**Issue by deke207** [Automattic/super-cool-ad-inserter-plugin#54]
Current live representation of the issue. [https://bangordailynews.com/2020/07/09/sports/professional-sports/mahomes-new-contract-is-unbelievable-but-hes-worth-it/](https://bangordailynews.com/2020/07/09/sports/professional-sports/mahomes-new-contract-is-unbelievable-but-hes-worth-it/)

![Screen Shot 2020-07-09 at 1 07 19 PM](https://user-images.githubusercontent.com/43453683/87069447-32ab9a80-c1e5-11ea-9733-d60d371eac44.jpg)

**Comment by benlk** [comment]
Can you send us the following, please?
- The post's `post_content`
- A description of what's in the inserted widget area
- Whether automatic ad insertion was enabled for this post or whether the post was using a shortcode or block instead

**Comment by claudiulodro** [comment]
[I think this should use the same popup injection logic as Newspack Campaigns.](https://github.com/Automattic/newspack-popups/pull/94)

**Comment by jeffersonrabb** [comment]
> I think this should use the same popup injection logic as Newspack Campaigns.

I agree, but we may need to keep the original logic intact to not break in Classic content. I believe the Newspack Campaigns implementation assumes Gutenberg (correctly!) but SCAI is possibly in use on sites with pre-Gutenberg content that may never be converted. We can detect Gutenberg content fairly easily, then apply the correct injection approach. WDYT?

**Comment by sonjaleix** [comment]
Hi team, wanted to check in on this issue to see if there has been any progress on resolving it. We're having the same issue still with ads being injected into group blocks. Thanks

**Comment by BurlesonBrad** [comment]
Similar behavior noted on the quote block as well.  Ad injects itself between the quote text and then the quote's author

### Here's the content as entered:
![image](https://user-images.githubusercontent.com/6208757/126917828-67a1caee-8ba9-4420-a519-ae26426bb70a.png)
-------------
### Then here's the content as rendered on the front end:
![image](https://user-images.githubusercontent.com/6208757/126917778-2acdd19c-1a89-4bed-a6d9-2c2b25be9680.png)

Any idea how to add 'exceptions' to these well needed ad injections?  
Thanks! -Brad

**Comment by benlk** [comment]
> I agree, but we may need to keep the original logic intact to not break in Classic content. I believe the Newspack Campaigns implementation assumes Gutenberg (correctly!) but SCAI is possibly in use on sites with pre-Gutenberg content that may never be converted. We can detect Gutenberg content fairly easily, then apply the correct injection approach. WDYT?

Honestly, you should probably rewrite the Classic ad inserter logic to use a DOM parser like the DOMDocument library, instead of using the naïve "insert after `</p>` solution that the plugin currently uses. https://github.com/Automattic/super-cool-ad-inserter-plugin/blob/d415db36ffae920991b2b299fc75e37ee9b6462a/inc/scaip-shortcode-inserter.php#L32-L36

It would be better to parse `post_content` for top-level elements, and then follow the classical logic of only inserting after paragraphs. By only parsing top-level elements, you'd avoid inserting between paragraph tags that are part of a block or other element's inner content.

**Comment by BurlesonBrad** [comment]
> By only parsing top-level elements

I ain't no rocket surgeon, or a brain scientist.  But I reckon that part right there sounds correct.
