### ISSUE TITLE
[WP 5.8] Error message in widgets block editor

### ISSUE THREAD

**Issue by dkoo** [Automattic/super-cool-ad-inserter-plugin#61]
In the new blocks-based widget editor, having the Super Cool Ad Inserter plugin active will result in an error message being shown at the top of the editor:

<img width="1148" alt="Screen Shot 2021-07-09 at 3 35 49 PM" src="https://user-images.githubusercontent.com/2230142/125138423-d74c0b00-e0cb-11eb-92c6-8e1ac2cd08e8.png">

**Comment by daria2303** [comment]
Another one: 4200471-zd-woothemes

Workaround: Classic Widgets plugin

**Comment by synora** [comment]
The ticket above has come off-hold and updates about this issue are being requested. 
p1630595750064200-slack-C01UW7SB411

**Comment by adekbadek** [comment]
I can't reproduce that neither on `master` nor on an earlier version. 

> In the new blocks-based widget editor, having the Super Cool Ad Inserter plugin active will result in an error message being shown at the top of the editor:

@dkoo - the error message mentions more details in the developer tools - could you please share those?

**Comment by dcoleonline** [comment]
I'm just adding a note to make sure we get back to the user in 4200471-zen once this is resolved. I'll close the ticket there as it's been on hold for some time.

**Comment by dkoo** [comment]
@adekbadek @dcoleonline I saw this error during the WP 5.8 beta testing. I can no longer replicate it on my test site nor a new ephemeral test site.

However, I took a look into ticket #4200471 and looked at the site in question, and it doesn't look like this site is using the Super Cool Ad Inserter plugin at all, so I don't believe this ticket is related to this particular GitHub issue.

**Comment by dkoo** [comment]
Since I can't replicate with SCAIP active on my test site or a new test site, I'm closing this issue as "can't replicate"/"won't fix". Steps to confirm:

1. On a new test site, disable the widget block editor using a filter, e.g.

```php
// Disables the block editor from managing widgets.
add_filter( 'use_widgets_block_editor', '__return_false' );
```

2. Install/activate SCAIP and in the classic widget editor, add some Text widgets to the SCAIP widget areas. Confirm that they render as expected in post content.

3. Re-enable the widget block editor and view the Widgets page. Confirm that there's no error message and the SCAIP widgets continue to be available in the editor and render in the expected placements on the front-end.
