### ISSUE TITLE
No insertion on classic posts (not blocks)

### ISSUE THREAD

**Issue by dkoo** [Automattic/super-cool-ad-inserter-plugin#93]
#78 fixed insertion logic to allow widgets to be inserted between paragraphs within Classic blocks, but this doesn't seem to be working for classic _posts_ that haven't yet been converted to blocks.

**Comment by miguelpeixe** [comment]
I was not able to reproduce the issue. I tested by using the [Classic Editor](https://wordpress.org/plugins/classic-editor/) plugin.

Can you provide the raw structure of the post that is failing?

**Comment by dkoo** [comment]
I think this turned out to be happening on posts that were being imported with content nested inside `div` markup—will confirm and close if that's the case.
